import React, { useEffect, useState } from 'react';

// ─── Types ───────────────────────────────────────────

type SectionId =
  | 'overview'
  | 'architecture'
  | 'pages'
  | 'modules'
  | 'integrations'
  | 'api'
  | 'database'
  | 'rendering'
  | 'config'
  | 'dataflow';

interface LiveColumn {
  name: string;
  type: string;
  notnull: number;
  dflt_value: string | null;
  pk: number;
}

interface LiveTable {
  name: string;
  columns: LiveColumn[];
  rowCount: number;
}

interface LiveRoute {
  method: string;
  path: string;
}

interface LiveMigration {
  version: number;
  name: string;
  applied_at: string;
}

interface LiveModule {
  dir: string;
  files: string[];
}

interface LiveData {
  generatedAt: string;
  tables: LiveTable[];
  routes: LiveRoute[];
  migrations: LiveMigration[];
  sourceContents: Record<string, string>;
  sourceTree: {
    config: string[];
    database: string[];
    integrations: string[];
    orchestrator: string[];
    rendering: string[];
    utils: string[];
    dashboard: string[];
    modules: LiveModule[];
    entryPoints: string[];
  };
  configSummary: {
    niche: string;
    dashboardPort: number;
    model: string;
    carouselSlideCount: number;
    hasInstagramToken: boolean;
    hasReplicateToken: boolean;
    hasCloudinary: boolean;
    hasOpenAI: boolean;
    hasBuffer: boolean;
  };
}

const sectionList: { id: SectionId; label: string }[] = [
  { id: 'overview', label: 'Overview' },
  { id: 'architecture', label: 'Architecture' },
  { id: 'dataflow', label: 'Data Flow' },
  { id: 'pages', label: 'Dashboard Pages' },
  { id: 'modules', label: 'Content Modules' },
  { id: 'integrations', label: 'External APIs' },
  { id: 'api', label: 'API Endpoints' },
  { id: 'database', label: 'Database' },
  { id: 'rendering', label: 'Rendering Pipeline' },
  { id: 'config', label: 'Configuration' },
];

// ─── Description Maps (enriches dynamic data) ────────

const tableDescriptions: Record<string, string> = {
  niches: 'Analyzed niches with 6-metric scoring. One selected as active.',
  content_ideas: 'Generated content ideas (carousel/reel/story/static) with hooks and triggers.',
  content_option_batches: 'Batch tracking for 5-option content generation. Status: generating/ready/selected/expired.',
  content_scripts: 'Production-ready scripts generated by Module 03. Full JSON structure + extracted fields.',
  rendered_assets: 'Rendered visual assets (PNGs, MP4s) with local paths and Cloudinary CDN URLs.',
  published_content: 'Published posts with Instagram analytics metrics. Refreshed daily.',
  brand_system: 'Brand identity: colors, typography, voice, visual style, content rules.',
  content_calendar: '4-week content schedule with pillar rotation and time slots.',
  revenue: 'Revenue entries by date and source for tracking monetization progress.',
  weekly_scorecard: 'Weekly KPI summaries with traffic-light health scoring.',
  email_list: 'Email subscribers captured via DM automation flows.',
  dm_flows: 'DM automation trigger-response flows (5-7 step sequences).',
  cross_platform_log: 'History of platform adaptations (TikTok, YouTube, Pinterest, Twitter).',
  api_costs: 'Claude API usage tracking for cost monitoring.',
  creative_briefs: 'Creative direction profiles guiding AI content generation.',
  ai_settings: 'AI behavior profiles: prompts, image style, temperature overrides.',
};

const routeDescriptions: Record<string, string> = {
  'GET /api/status': 'Get current pipeline state (phase, lastRun, errors, todaysPackage)',
  'POST /api/pipeline/run': 'Trigger full daily pipeline manually',
  'POST /api/pipeline/auto-run': 'Render daily package + auto-publish to Instagram',
  'GET /api/queue': 'List all content scripts with ideas, assets (limit 50)',
  'GET /api/queue/pending': 'Scripts awaiting approval',
  'GET /api/queue/ready': 'Approved scripts ready to publish',
  'POST /api/queue/:id/approve': 'Approve content script',
  'POST /api/queue/:id/reject': 'Reject content script',
  'POST /api/queue/:id/approve-content': 'Approve and trigger visual rendering',
  'POST /api/queue/:id/regenerate': 'Regenerate visual assets for script',
  'POST /api/queue/:id/publish': 'Publish script to Instagram (manual method)',
  'POST /api/queue/:id/approve-and-post': 'Auto-publish designed script to Instagram',
  'POST /api/queue/:id/approve-and-schedule': 'Approve and add to content calendar',
  'GET /api/schedule': 'Get all scheduled content entries',
  'POST /api/schedule/:calendarId/remove': 'Remove entry from schedule',
  'POST /api/schedule/:calendarId/publish-now': 'Publish scheduled entry immediately',
  'POST /api/options/generate': 'Generate 5 content option variations',
  'GET /api/options/latest': 'Get latest content option batch',
  'GET /api/briefs': 'List all creative briefs',
  'GET /api/briefs/active': 'Get currently active brief',
  'POST /api/briefs': 'Create new brief (auto-activates, deactivates others)',
  'PUT /api/briefs/:id': 'Update existing brief',
  'POST /api/briefs/:id/activate': 'Set brief as active',
  'DELETE /api/briefs/:id': 'Delete brief',
  'GET /api/ai-settings': 'List all AI settings profiles',
  'GET /api/ai-settings/active': 'Get active settings profile',
  'GET /api/ai-settings/defaults': 'Get hardcoded default values (for Reset to Default)',
  'POST /api/ai-settings': 'Create new profile (auto-activates)',
  'PUT /api/ai-settings/:id': 'Update profile fields',
  'POST /api/ai-settings/:id/activate': 'Activate specific profile',
  'DELETE /api/ai-settings/:id': 'Delete profile',
  'GET /api/analytics': 'Published posts from last 30 days, sorted by sends/reach',
  'POST /api/analytics/refresh': 'Pull fresh metrics from Instagram Graph API',
  'GET /api/scorecard': 'Generate weekly scorecard with traffic-light KPIs',
  'GET /api/scorecard/history': 'All historical weekly scorecards',
  'GET /api/revenue': 'List all revenue entries',
  'GET /api/revenue/overview': 'Revenue summary (total, this month, by source)',
  'POST /api/revenue': 'Add revenue entry (date, source, description, amount)',
  'POST /api/revenue/strategy': 'AI-generate monetization strategy for follower count',
  'GET /api/design': 'Get current design system direction',
  'POST /api/design/generate': 'AI-generate new design system for active niche',
  'GET /api/calendar': 'Upcoming 4-week content calendar',
  'GET /api/calendar/today': "Today's scheduled content",
  'POST /api/calendar/generate': 'Generate 4-week calendar with pillar rotation',
  'GET /api/niches': 'List analyzed niches with scores',
  'GET /api/trends': 'Scan current trending topics in niche',
  'POST /api/engagement/protocol': 'Generate engagement protocol (pre/post actions)',
  'GET /api/roadmap/phase': 'Get current growth phase for follower count',
  'POST /api/roadmap/generate': 'Generate scaling roadmap (0 to 100K+)',
  'GET /api/dm-flows': 'List active DM automation flows',
  'POST /api/dm-flows': 'Create new DM flow (keyword + value)',
  'POST /api/dm-flows/lead-magnets': 'Generate lead magnet ideas',
  'GET /api/email-list': 'Email list stats from DM captures',
  'GET /api/cross-platform': 'Cross-platform adaptation log',
  'GET /api/cross-platform/stats': 'Distribution stats per platform',
  'POST /api/cross-platform/adapt': 'Adapt script for target platform (TikTok, YT, etc.)',
  'POST /api/render/:id': 'Render visual assets for a specific script',
  'POST /api/fingerprint/audit': 'Audit queued content for originality violations',
  'GET /api/build-doc': 'Auto-discovery endpoint for this build document',
};

const moduleDescriptions: Record<string, { name: string; description: string; exports: string[] }> = {
  '00-originality': { name: 'Originality Architecture', description: "Ensures all content avoids Instagram's repost/aggregator penalties. Sets transformation rules, red lines, and runs 70%+ similarity detection on queued content.", exports: ['generateOriginalityStrategy()', 'auditQueue()'] },
  '01-niche-selector': { name: 'Niche Selector', description: 'Analyzes 20 niches on 6 scoring metrics: DM shareability, evergreen demand, monetization ceiling, originality viability, search SEO, subscription ceiling.', exports: ['analyzeNiches()', 'selectNiche()'] },
  '02-viral-blueprint': { name: 'Viral Content Blueprint', description: 'Generates 15 viral content ideas (8 carousel + 7 reel) with hooks, value propositions, emotional triggers, and send triggers.', exports: ['generateViralBlueprint()'] },
  '03-content-builder': { name: 'Content Builder', description: 'Converts ideas into production-ready scripts. Carousel: 10-slide hook/value/CTA structure. Reel: timed segments with per-segment voiceover scripts (field names: voiceover, voiceoverScript, audio), visual descriptions, and timestamp ranges. Story: 6-8 slides with interactive elements.', exports: ['buildCarousel()', 'buildReel()', 'buildStorySequence()'] },
  '04-daily-output': { name: 'Daily Output Engine', description: 'Assembles daily content package: trend scan, carousel idea, reel idea, story sequence. Options engine generates 5 variations for user selection.', exports: ['generateDailyPackage()', 'generateContentOptions()', 'getLatestBatch()', 'scanTrends()'] },
  '05-design-system': { name: 'Design System', description: 'AI-generated brand visual system: color palette, typography, layout rules, mood board, template variations. Feeds into rendering pipeline.', exports: ['generateDesignSystem()', 'getDesignDirection()'] },
  '06-growth-strategy': { name: 'Growth Strategy', description: '4-week content calendar with pillar rotation and optimal posting times. Engagement protocol: pre-post and post-post actions.', exports: ['generateContentCalendar()', 'getUpcomingCalendar()', 'generateEngagementProtocol()'] },
  '07-monetization': { name: 'Monetization', description: 'Revenue strategy with 5+ streams (courses, affiliate, sponsorships, digital products). Milestone targets by follower count.', exports: ['generateRevenueStrategy()', 'getRevenueOverview()'] },
  '08-scaling': { name: 'Scaling Roadmap', description: 'Growth roadmap from 0 to 100K+ followers. Phase detection, next milestone identification, growth levers with impact scores.', exports: ['generateRoadmap()', 'getCurrentPhase()'] },
  '09-dm-automation': { name: 'DM Automation', description: 'Trigger-based DM flows (5-7 step sequences) with email capture. Lead magnet generation. Designed for ManyChat integration.', exports: ['createDMFlow()', 'generateLeadMagnets()', 'getActiveDMFlows()', 'getEmailListStats()'] },
  '10-cross-platform': { name: 'Cross-Platform', description: 'Adapts Instagram content for TikTok, YouTube Shorts, Pinterest, and Twitter. Platform-specific formatting, hooks, captions, hashtags.', exports: ['adaptForPlatform()', 'getCrossPlatformLog()', 'getDistributionStats()'] },
};

// ─── Markdown Generator ──────────────────────────────

function generateMarkdown(sectionId: SectionId | 'all', live: LiveData | null): string {
  const L: string[] = [];
  const src = live?.sourceContents || {};
  const hr = () => L.push('', '---', '');
  const h1 = (t: string) => L.push(`# ${t}`);
  const h2 = (t: string) => L.push('', `## ${t}`);
  const h3 = (t: string) => L.push('', `### ${t}`);
  const h4 = (t: string) => L.push('', `#### ${t}`);
  const p = (t: string) => L.push('', t);
  const bullet = (t: string) => L.push(`- ${t}`);
  const codeBlock = (lang: string, code: string) => L.push('', '```' + lang, code, '```');
  const fileBlock = (filePath: string) => {
    const content = src[filePath];
    if (content) {
      const ext = filePath.endsWith('.tsx') ? 'tsx' : 'ts';
      codeBlock(ext, content);
    }
  };
  const inc = (id: SectionId) => sectionId === 'all' || sectionId === id;

  // ─── Title ───────────────────────────────────────
  if (sectionId === 'all') {
    h1('ThePlantICU Content Engine — Complete Build Document');
    p(`**Generated:** ${live?.generatedAt ? new Date(live.generatedAt).toLocaleString() : new Date().toLocaleString()}`);
    p('This document contains the complete technical specification, architecture, source code, database schema, API reference, and operational details for the ThePlantICU Content Engine — an AI-powered, faceless Instagram content automation platform built for the @ThePlantICU plant care theme page.');
    p('This application is designed as a **foundation template** that can be cloned and reconfigured for any niche Instagram theme page.');
    hr();
  }

  // ─── OVERVIEW ────────────────────────────────────
  if (inc('overview')) {
    h2('1. Overview');

    h3('1.1 What Is This Application?');
    p('ThePlantICU Content Engine is a full-stack application that automates the entire Instagram content lifecycle for a faceless theme page. It uses Claude AI (Anthropic) to generate content ideas, write production-ready scripts, and compose visual descriptions. Those scripts are then rendered into publishable assets (carousel PNGs, reel MP4 videos, story frames) using Puppeteer, Replicate AI image generation, OpenAI text-to-speech, and ffmpeg. The finished assets are uploaded to Cloudinary and published to Instagram via the Graph API.');
    p('A React dashboard provides a browser-based control center for approving content, configuring AI behavior, tracking analytics, managing revenue, and monitoring the entire pipeline.');

    h3('1.2 Core Design Principles');
    bullet('**Zero-Face Content** — No person ever appears on camera. All visual content is AI-generated backgrounds with text overlays. This enables fully automated content production without filming.');
    bullet('**100% Original** — Every piece of content is generated from scratch by Claude AI. A built-in originality engine (Module 00) audits content for similarity above 70% and flags potential reposts. Instagram penalizes aggregator accounts that repost — this engine ensures every post is original.');
    bullet('**DM-First Growth Strategy** — The #1 Instagram algorithm signal in 2026 is "sends per reach" — how many people DM a post to someone else. Every piece of content is optimized to answer: "Who would DM this to whom?" This drives organic reach far more than likes or comments.');
    bullet('**Human Approval Gate** — AI generates content, but nothing publishes automatically without explicit human approval from the dashboard. This prevents off-brand or low-quality content from reaching the audience.');
    bullet('**Full Automation Pipeline** — The system handles every step: trend scanning, idea generation, script writing, visual rendering, CDN upload, Instagram publishing, and post-publish analytics. The operator only needs to approve content and adjust creative direction.');
    bullet('**Analytics Feedback Loop** — Real performance metrics (impressions, reach, sends, saves, engagement rate) are pulled from Instagram Graph API daily. Weekly scorecards with traffic-light health indicators (green/yellow/red) surface what\'s working and what needs adjustment.');

    h3('1.3 Tech Stack');
    p('**Backend Runtime:** Node.js with TypeScript, compiled via `tsc` to ES modules.');
    p('**Web Framework:** Express.js serving both the REST API and the static React dashboard.');
    p('**Frontend:** React 18 with TypeScript, built by Vite, styled with Tailwind CSS (CDN).');
    p('**Database:** SQLite via `better-sqlite3` — single-file database with WAL mode and foreign keys. Zero configuration, perfect for a single-operator tool.');
    p('**CLI:** Commander.js providing 25+ terminal commands for headless operation.');
    p('**AI Content Generation:** Anthropic Claude API (Sonnet 4.5 by default) for all text generation. Includes JSON repair logic for truncated responses.');
    p('**AI Image Generation:** Replicate API running Black Forest Labs Flux Schnell for background images in 9:16 (reels) and 1:1 (carousels) aspect ratios.');
    p('**Voiceover:** OpenAI Text-to-Speech API (tts-1 model) with 6 voice options for reel narration. Per-segment TTS generation ensures voiceover is perfectly synced with visuals — audio duration drives each segment\'s visual length.');
    p('**Visual Rendering:** Puppeteer (headless Chrome) renders HTML/CSS templates to PNG screenshots. ffmpeg composes reel MP4 videos with Ken Burns zoom effect, crossfade transitions, and per-segment audio-synced timing.');
    p('**CDN:** Cloudinary for hosting rendered assets with public HTTPS URLs (required by Instagram Graph API for publishing).');
    p('**Publishing:** Instagram Graph API v22.0 for carousel, reel, and image post publishing. Buffer API v1 as optional scheduling alternative.');

    if (live) {
      h3('1.4 Active Configuration');
      bullet(`Active niche: **${live.configSummary.niche || '(not set)'}**`);
      bullet(`Claude model: \`${live.configSummary.model}\``);
      bullet(`Dashboard port: ${live.configSummary.dashboardPort}`);
      bullet(`Carousel slide count: ${live.configSummary.carouselSlideCount}`);
      bullet(`Instagram API: ${live.configSummary.hasInstagramToken ? 'Connected' : 'Not connected'}`);
      bullet(`Replicate API: ${live.configSummary.hasReplicateToken ? 'Connected' : 'Not connected'}`);
      bullet(`Cloudinary: ${live.configSummary.hasCloudinary ? 'Connected' : 'Not connected'}`);
      bullet(`OpenAI TTS: ${live.configSummary.hasOpenAI ? 'Connected' : 'Not connected'}`);
      bullet(`Buffer: ${live.configSummary.hasBuffer ? 'Connected' : 'Not connected'}`);
    }
  }

  // ─── ARCHITECTURE ────────────────────────────────
  if (inc('architecture')) {
    h2('2. Architecture & Project Structure');

    h3('2.1 Directory Layout');
    if (live) {
      const tree: string[] = ['src/'];
      live.sourceTree.entryPoints.forEach(f => tree.push(`  ${f}`));
      const cats = [
        { label: 'config', files: live.sourceTree.config },
        { label: 'database', files: live.sourceTree.database },
        { label: 'integrations', files: live.sourceTree.integrations },
        { label: 'orchestrator', files: live.sourceTree.orchestrator },
        { label: 'rendering', files: live.sourceTree.rendering },
        { label: 'utils', files: live.sourceTree.utils },
      ];
      cats.forEach(c => { tree.push(`  ${c.label}/`); c.files.forEach(f => tree.push(`    ${f.replace(c.label + '/', '')}`)); });
      tree.push('  modules/');
      live.sourceTree.modules.forEach(m => { tree.push(`    ${m.dir}/`); m.files.forEach(f => tree.push(`      ${f}`)); });
      tree.push('  dashboard/');
      live.sourceTree.dashboard.forEach(f => tree.push(`    ${f.replace('dashboard/', '')}`));
      tree.push('data/');
      tree.push('  ig-engine.db');
      tree.push('  assets/');
      codeBlock('', tree.join('\n'));
    }

    h3('2.2 Entry Points');

    h4('`src/index.ts` — CLI Interface');
    p('Commander.js CLI with 25+ commands for headless operation. Commands include: `niches`, `select-niche`, `originality`, `design-system`, `blueprint`, `daily`, `start`, `status`, `trends`, `generate-options`, `queue`, `approve`, `reject`, `publish`, `render`, `analytics`, `scorecard`, `calendar`, `engagement`, `monetize`, `roadmap`, `dm-flow`, `lead-magnets`, `cross-platform`, `fingerprint`.');
    fileBlock('index.ts');

    h4('`src/server.ts` — Express REST API + Dashboard Server');
    p('The main server file defines all API endpoints, runs database migrations on startup, and serves the compiled React dashboard as static files. All CRUD operations, pipeline triggers, and content management flow through this file.');
    fileBlock('server.ts');

    h3('2.3 Key Design Decisions');
    bullet('**SQLite over Postgres** — Single-file database at `data/ig-engine.db`. Zero configuration, no separate database server. WAL (Write-Ahead Logging) mode enables concurrent reads during writes. Foreign keys enforced. Perfect for a single-operator content tool.');
    bullet('**Puppeteer for rendering** — HTML/CSS templates are rendered to pixel-perfect PNG screenshots using headless Chrome. This gives full control over typography, gradient backgrounds, text shadows, and responsive layouts without needing a design tool API.');
    bullet('**Module numbering (00-10)** — Each module represents a sequential stage in the content pipeline. Self-contained with its own prompts file, engine file, and types. Modules can be run independently via CLI or orchestrated together by the master pipeline.');
    bullet('**Creative Brief + AI Settings split** — Two separate configuration systems: the Creative Brief defines *what* content to make (angles, mood, competitor inspiration, target emotions). AI Settings defines *how* the AI behaves (system prompt personality, image style modifiers, temperature). This separation lets the operator change creative direction without touching AI parameters, and vice versa.');
  }

  // ─── DATA FLOW ───────────────────────────────────
  if (inc('dataflow')) {
    h2('3. Data Flow & Pipeline');

    h3('3.1 Content Pipeline (11 Steps)');
    p('The content pipeline is a sequential workflow that transforms a blank slate into a published Instagram post with tracked analytics:');
    [
      '**Step 1 — Niche Selection:** Module 01 analyzes 20 potential niches, scoring each on 6 metrics (DM shareability, evergreen demand, monetization ceiling, originality viability, search SEO, subscription ceiling). The highest-scoring niche is selected and stored in the database.',
      '**Step 2 — Originality Rules:** Module 00 generates an originality architecture — transformation rules, red lines, and plagiarism detection thresholds. This ensures every piece of content passes Instagram\'s repost detection (which penalizes accounts with 70%+ similarity or 10+ reposts in 30 days).',
      '**Step 3 — Viral Blueprint:** Module 02 generates 15 content ideas (8 carousels + 7 reels) with hooks, value propositions, emotional triggers, send triggers, and format notes. Each idea is scored on "send probability" — the likelihood someone would DM it to a friend.',
      '**Step 4 — Trend Check:** Module 04 scans for trending topics in the active niche. Each trend is urgency-ranked (trending/viral/emerging) and paired with an original angle that avoids being derivative.',
      '**Step 5 — Content Options:** Module 04 generates 5 variations of a content idea (different angles, hooks, formats) so the operator can choose the strongest direction before committing to full script generation.',
      '**Step 6 — Script Building:** Module 03 takes the selected idea and produces a production-ready script. For carousels: 10-slide structure with hook/value/CTA slides, headlines, body text, AI image prompts (designNotes), and text hierarchy. For reels: timed segments with timestamp ranges (e.g. "4-7s"), on-screen text, per-segment voiceover scripts, visual descriptions, and pacing notes. The renderer parses multiple Claude field name variants (voiceover, voiceoverScript, audio) and timestamp formats ("4-7s", "0:02-0:05").',
      '**Step 7 — Approval Gate:** The operator reviews the script in the dashboard Content page. They can approve (moves to rendering), reject (archives), or edit the script. Nothing proceeds without explicit human action.',
      '**Step 8 — Visual Rendering:** Approved scripts are rendered into publishable assets. Carousel slides: Puppeteer screenshots of HTML templates at 1080x1080 with AI-generated backgrounds from Replicate. Reels: per-segment TTS voiceover generated first (audio drives timing), then AI background images + text overlay PNGs, composed into MP4 video by ffmpeg with Ken Burns zoom, crossfade transitions, and audio-synced segment durations.',
      '**Step 9 — CDN Upload:** Rendered assets (PNGs, MP4s) are uploaded to Cloudinary, which provides public HTTPS URLs. Instagram Graph API requires publicly accessible URLs to create media containers.',
      '**Step 10 — Publishing:** The operator triggers "Post to Instagram" from the dashboard. The system calls Instagram Graph API to create media containers and publish the post. Carousel posts use `createCarouselItemContainer()` for each slide, then `createCarouselContainer()` + `publishMedia()`. Reels use `publishReel()` with the video URL.',
      '**Step 11 — Analytics:** Instagram Graph API insights are pulled daily via `refreshAnalytics()`. Metrics tracked: impressions, reach, sends, saves, likes, comments, shares, video views, watch time. Computed metrics: sends/reach %, likes/reach %, engagement rate. Weekly scorecards grade performance with traffic-light indicators.',
    ].forEach(bullet);

    h3('3.2 Status Lifecycle');
    codeBlock('', 'Content Idea Status Flow:\n  generated → scripted → approved → designed → published\n                  ↘ rejected → archived\n\nPipeline Phase:\n  idle → generating → rendering → awaiting_approval → publishing → idle\n\nContent Calendar Entry:\n  scheduled → published | cancelled');

    h3('3.3 AI Settings Impact Map');
    p('When an AI Settings profile is active, its values override hardcoded defaults at specific points in the pipeline:');
    bullet('**content_builder_system** → Replaces the Claude system prompt in `carousel-builder.ts`, `reel-builder.ts`, and `story-builder.ts`. Controls the AI\'s personality, rules, and content style.');
    bullet('**carousel_design_instruction** → Replaces the designNotes instruction in `carouselBuilderPrompt()`. Controls how Claude describes the visual scene for each carousel slide.');
    bullet('**reel_visual_instruction** → Replaces the visual instruction in `reelBuilderPrompt()`. Applied to hook visual, each body segment visual, and CTA visual fields.');
    bullet('**image_style_prefix** → Prepended to every prompt sent to Replicate Flux Schnell in `generateBackground()`. Example: "cinematic, 8k, dramatic lighting, high detail".');
    bullet('**image_style_suffix** → Appended to every Replicate prompt. Example: "sharp focus, professional photography, no text".');
    bullet('**image_negative_prompt** → Appended as "Do not include: ..." to every Replicate prompt. Example: "blurry, low quality, text, watermark, deformed".');
    bullet('**temperature** → Overrides the default 0.7 temperature for all Claude API calls. Lower = more focused/predictable. Higher = more creative/varied.');
  }

  // ─── DASHBOARD PAGES ─────────────────────────────
  if (inc('pages')) {
    h2('4. Dashboard Pages');
    p('The dashboard is a React single-page application served as static files by Express. All pages are tab-navigated from `App.tsx`. Each page communicates with the backend via `fetch()` calls to `/api/*` endpoints.');

    h4('`src/dashboard/App.tsx` — Shell & Navigation');
    p('The root component. Renders the header with ThePlantICU branding, tab navigation bar, and the active page component. Tabs: Pipeline, Content, Brief, AI Settings, Analytics, Scorecard, Revenue, Build Checklist, Build Doc.');
    fileBlock('dashboard/App.tsx');

    const dashPages = [
      { file: 'dashboard/pages/PipelineStatus.tsx', name: 'Pipeline Status', desc: 'Displays current pipeline phase (idle/generating/rendering/publishing) with color-coded status, last run timestamp, error log, and today\'s content package preview (carousel, reel, stories with DM triggers). Includes a "Run Daily Pipeline" button that triggers the full generate→render→approve workflow. Auto-refreshes every 5 seconds.' },
      { file: 'dashboard/pages/Content.tsx', name: 'Content', desc: 'The main content management hub. Shows all queued content scripts with visual thumbnail previews of rendered carousel slides. Actions per item: "Approve & Render" (triggers Puppeteer/Replicate rendering), "Regenerate" (re-renders with new AI backgrounds), "Post to Instagram" (publishes via Graph API), "Schedule for Later" (adds to content calendar). Displays caption text, hashtags, DM trigger keywords, and content type badges.' },
      { file: 'dashboard/pages/CreativeBrief.tsx', name: 'Creative Brief', desc: 'CRUD interface for creative direction profiles. Each brief contains: title, notes/inspiration, competitor Instagram links (parsed from URLs), content angles (tag-style chips), mood & themes, visual style, and target emotions. The active brief (green border) guides AI content generation. Past briefs are listed with Activate/Edit/Delete buttons. Creating a new brief auto-deactivates the previous one.' },
      { file: 'dashboard/pages/AISettings.tsx', name: 'AI Settings', desc: 'CRUD interface for AI behavior profiles. Four sections: (1) Claude Personality — system prompt textarea with Reset to Default, (2) Image Prompt Instructions — carousel design instruction and reel visual instruction textareas, (3) Image Generation Style — style prefix, suffix, and negative prompt inputs that modify Replicate prompts, (4) Model Parameters — temperature slider from 0.0 to 1.0. Profiles can be versioned, activated, and compared.' },
      { file: 'dashboard/pages/Analytics.tsx', name: 'Analytics', desc: '30-day performance overview. Summary cards: total reach, total sends, total saves, average engagement rate, average sends/reach %. Per-post table sorted by sends/reach showing every published post with individual metrics. "Refresh Analytics" button pulls latest data from Instagram Graph API.' },
      { file: 'dashboard/pages/Scorecard.tsx', name: 'Scorecard', desc: 'Weekly KPI dashboard. Each metric gets a traffic-light health status: green (healthy), yellow (needs attention), red (critical). Tracked KPIs: sends/reach %, engagement rate, posts published per week, revenue. Historical scorecard comparison shows trends over time.' },
      { file: 'dashboard/pages/Revenue.tsx', name: 'Revenue', desc: 'Revenue tracking dashboard. Manual entry form (date, source, description, amount). Summary cards: total revenue, this month, last month. By-source breakdown. AI strategy generator that takes current follower count and recommends revenue streams, pricing, and setup steps.' },
      { file: 'dashboard/pages/BuildChecklist.tsx', name: 'Build Checklist', desc: 'Development progress tracker with 70+ items across 18 sections (project scaffold, database, Claude client, modules 0-10, orchestrator, analytics, CLI, dashboard, integrations, utilities). Each item is marked Done/Partial/Missing with optional notes. Overall completion percentage and section-level progress bars.' },
      { file: 'dashboard/pages/BuildDoc.tsx', name: 'Build Document', desc: 'This page. Auto-updating technical documentation that fetches live data from `/api/build-doc` (database schema, API routes, source file tree, config status). Download buttons generate comprehensive Markdown files with full source code included.' },
      { file: 'dashboard/pages/ContentOptions.tsx', name: 'Content Options', desc: 'Shows the 5 content option variations from the latest generation batch. Each option displays the idea title, hook, format type, send trigger, and send probability score. The operator selects their preferred option to proceed to script building.' },
    ];

    dashPages.forEach(pg => {
      h3(`4.${dashPages.indexOf(pg) + 1} ${pg.name} Page`);
      p(pg.desc);
      h4(`Source: \`src/${pg.file}\``);
      fileBlock(pg.file);
    });
  }

  // ─── MODULES ─────────────────────────────────────
  if (inc('modules')) {
    h2('5. Content Generation Modules');
    p('The application is organized into 11 sequential modules (00-10), each handling a specific stage of the content pipeline. Every module is self-contained in its own directory under `src/modules/` with its own engine file(s) and prompts file.');

    const mods = live?.sourceTree.modules || [];
    mods.forEach((m, mi) => {
      const info = moduleDescriptions[m.dir];
      h3(`5.${mi + 1} Module ${m.dir}${info ? ' — ' + info.name : ''}`);
      if (info) {
        p(info.description);
        p(`**Key exports:** ${info.exports.map(e => '`' + e + '`').join(', ')}`);
      }
      m.files.forEach(f => {
        h4(`\`src/modules/${m.dir}/${f}\``);
        fileBlock(`modules/${m.dir}/${f}`);
      });
    });
  }

  // ─── INTEGRATIONS ────────────────────────────────
  if (inc('integrations')) {
    h2('6. External API Integrations');
    p('All external service clients live in `src/integrations/`. Each file wraps a third-party API with typed functions, error handling, and cost tracking where applicable.');

    const integrations = [
      { name: 'Anthropic Claude API', file: 'integrations/claude-client.ts', desc: 'Wraps the Anthropic SDK for all AI text generation. Two main functions: `askClaude()` returns raw text responses with token counts and cost estimates. `askClaudeJSON<T>()` adds structured JSON parsing with a 3-tier repair system: direct parse → JSON block extraction via regex → truncated JSON repair (auto-closes unclosed brackets and braces). Cost estimation uses Sonnet 4.5 pricing ($3/M input tokens, $15/M output tokens). The temperature default is dynamically read from AI Settings via `getSetting(\'temperature\', 0.7)`.' },
      { name: 'Instagram Graph API', file: 'integrations/instagram-api.ts', desc: 'Full Instagram publishing client using Graph API v22.0. Supports three post types: single image (`publishImagePost`), multi-image carousel (`publishCarouselPost` — creates individual item containers, then a carousel container, waits for processing, and publishes), and video reel (`publishReel`). Also fetches account info, media insights (impressions, reach, saves, shares, video_views, ig_reels_avg_watch_time), and recent posts. Includes long-lived token exchange (short-lived → 60-day token) and token refresh. Container status polling with configurable timeout.' },
      { name: 'Replicate (Flux Schnell)', file: 'integrations/replicate-api.ts', desc: 'AI background image generation using Black Forest Labs Flux Schnell model. `generateBackground()` takes a text prompt, output directory, filename, and aspect ratio (default 9:16). Before calling Replicate, it reads the active AI Settings profile and injects `image_style_prefix` (prepended), `image_style_suffix` (appended), and `image_negative_prompt` (appended as "Do not include: ..."). Handles both URL string and ReadableStream output formats from Replicate. Saves PNG to local filesystem.' },
      { name: 'Cloudinary', file: 'integrations/cloudinary-api.ts', desc: 'Media CDN hosting for rendered assets. `uploadImage()` uploads a single image file and returns a public HTTPS URL. `uploadVideo()` does the same for MP4 files. `uploadImages()` batch-uploads an array of image paths. All uploads are organized into folders: `ig-engine/carousel-{id}`, `ig-engine/reel-{id}`. Public URLs are required by Instagram Graph API for media container creation.' },
      { name: 'OpenAI Text-to-Speech', file: 'integrations/tts-api.ts', desc: 'Reel voiceover generation using OpenAI TTS API (model: tts-1). `generateSpeech()` takes text and a voice option (alloy, echo, fable, onyx, nova, shimmer) and returns an MP3 audio file. Called once per reel segment (hook, each body segment, CTA) to produce individually-timed audio clips. Each clip\'s actual duration is probed via ffprobe and used to set the corresponding visual segment length, ensuring perfect audio-visual sync. Clips are concatenated into a single voiceover track via ffmpeg.' },
      { name: 'Buffer', file: 'integrations/buffer-api.ts', desc: 'Optional social media scheduling integration. Provides queue management (`addToQueue`, `getQueuedPosts`), direct scheduling (`schedulePost` with specific datetime), posting schedule configuration (`getPostingSchedule`, `updatePostingSchedule`), and post lifecycle management (`deletePost`, `moveToTop`). Alternative to direct Instagram Graph API publishing when scheduled posting is preferred.' },
      { name: 'Canva Connect', file: 'integrations/canva-api.ts', desc: 'Optional design creation API. `createDesign()` and `exportDesign()` use Canva Connect API for programmatic design generation. `generateDesignSpec()` provides a local fallback that generates design specifications without requiring Canva API approval. Primarily used for complex design workflows that exceed Puppeteer template capabilities.' },
    ];

    integrations.forEach((intg, i) => {
      h3(`6.${i + 1} ${intg.name}`);
      p(intg.desc);
      h4(`Source: \`src/${intg.file}\``);
      fileBlock(intg.file);
    });

    // Include any extra integration files
    const knownFiles = new Set(integrations.map(i => i.file));
    const extra = (live?.sourceTree.integrations || []).filter(f => !knownFiles.has(f));
    extra.forEach(f => {
      h4(`\`src/${f}\``);
      fileBlock(f);
    });
  }

  // ─── API ENDPOINTS ───────────────────────────────
  if (inc('api')) {
    h2('7. API Endpoint Reference');
    const routes = live?.routes.filter(r => r.path.startsWith('/api/')) || [];
    p(`The Express server exposes **${routes.length || '65+'}** REST API endpoints on port ${live?.configSummary.dashboardPort || 3847}. All endpoints return JSON. POST and PUT endpoints accept \`application/json\` request bodies.`);

    // Group by path prefix
    const groups: Record<string, typeof routes> = {};
    routes.forEach(r => {
      const prefix = r.path.replace('/api/', '').split('/')[0];
      if (!groups[prefix]) groups[prefix] = [];
      groups[prefix].push(r);
    });

    if (routes.length > 0) {
      Object.entries(groups).forEach(([group, eps]) => {
        h3(group.replace(/-/g, ' ').replace(/\b\w/g, c => c.toUpperCase()));
        L.push('', '| Method | Path | Description |', '|--------|------|-------------|');
        eps.forEach(r => {
          const key = `${r.method} ${r.path}`;
          const desc = routeDescriptions[key] || '*(undocumented)*';
          L.push(`| \`${r.method}\` | \`${r.path}\` | ${desc} |`);
        });
      });
    } else {
      L.push('', '| Method | Path | Description |', '|--------|------|-------------|');
      Object.entries(routeDescriptions).forEach(([key, desc]) => {
        const [method, ...rest] = key.split(' ');
        L.push(`| \`${method}\` | \`${rest.join(' ')}\` | ${desc} |`);
      });
    }

    p('The full implementation of all endpoints is in `src/server.ts` (included in the Architecture section above).');
  }

  // ─── DATABASE ────────────────────────────────────
  if (inc('database')) {
    h2('8. Database Schema');
    const tables = live?.tables || [];
    const migrations = live?.migrations || [];
    p(`SQLite database at \`data/ig-engine.db\`. **${tables.length} tables**, **${migrations.length} migrations** applied. WAL mode enabled for concurrent reads. Foreign keys enforced.`);

    if (migrations.length > 0) {
      h3('8.1 Migration History');
      L.push('', '| Version | Name | Applied |', '|---------|------|---------|');
      migrations.forEach(m => L.push(`| v${m.version} | ${m.name} | ${m.applied_at} |`));
    }

    h4('Source: `src/database/schema.ts`');
    fileBlock('database/schema.ts');

    h4('Source: `src/database/migrations.ts`');
    fileBlock('database/migrations.ts');

    h4('Source: `src/database/db.ts`');
    fileBlock('database/db.ts');

    if (tables.length > 0) {
      h3('8.2 Table Schemas (Live)');
      tables.forEach(t => {
        h4(`\`${t.name}\` (${t.rowCount} rows)`);
        p(tableDescriptions[t.name] || '');
        L.push('', '| Column | Type | Nullable | Default | PK |', '|--------|------|----------|---------|-----|');
        t.columns.forEach(c => {
          L.push(`| \`${c.name}\` | ${c.type || 'TEXT'} | ${c.notnull ? 'NO' : 'YES'} | ${c.dflt_value ? '`' + c.dflt_value + '`' : '-'} | ${c.pk ? 'YES' : ''} |`);
        });
      });
    }
  }

  // ─── RENDERING ───────────────────────────────────
  if (inc('rendering')) {
    h2('9. Rendering Pipeline');
    p('The rendering pipeline converts JSON content scripts into publishable visual assets. It uses Puppeteer (headless Chrome) for HTML→PNG rendering, Replicate Flux Schnell for AI background images, OpenAI TTS for voiceover audio, and ffmpeg for video composition.');

    h3('9.1 Carousel Rendering');
    p('Carousels are rendered as a set of 1080x1080 PNG images (one per slide). Each slide has an AI-generated background image with text overlays for the headline, body, and CTA.');
    bullet('Parse the script JSON into slide objects with type (hook/value/CTA), headline, bodyText, designNotes, and textHierarchy');
    bullet('For each slide, call `generateBackground()` with the designNotes as the prompt and 1:1 aspect ratio');
    bullet('Render an HTML template (`hookSlideHtml`, `valueSlideHtml`, or `ctaSlideHtml`) with the background image, brand colors, fonts, and text content');
    bullet('Screenshot the HTML with Puppeteer at 1080x1080 resolution');
    bullet('Upload all slide PNGs to Cloudinary');

    h3('9.2 Reel Rendering');
    p('Reels are rendered as MP4 videos with AI backgrounds, text overlays, and per-segment voiceover. Audio drives timing — each segment\'s visual duration is set by its voiceover audio length, ensuring perfect sync between voice, text, and visuals.');
    bullet('**Step 1 — Parse script JSON:** Extract segments (hook, body[], CTA) with on-screen text, voiceover scripts, visual descriptions, and timestamps. Supports multiple Claude timestamp formats: `"4-7s"`, `"0:02-0:05"`. Voiceover text is extracted from varying field names (`voiceover`, `voiceoverScript`, `audio`) with stage direction stripping.');
    bullet('**Step 2 — Per-segment TTS:** Generate OpenAI TTS audio for each segment individually (hook, each body segment, CTA). Probe each audio clip\'s actual duration via ffprobe, then set the visual segment duration = audio duration + 0.3s buffer. This ensures the voice narrates the entire reel without abrupt cutoffs.');
    bullet('**Step 3 — AI backgrounds:** Generate per-segment background images via Replicate Flux Schnell (9:16 aspect). Falls back to branded gradient backgrounds if Replicate fails.');
    bullet('**Step 4 — Text overlays:** Render transparent PNG overlays via Puppeteer using `reelOverlayHtml()` templates with step indicators for body segments.');
    bullet('**Step 5 — Audio stitching:** Concatenate all per-segment audio clips into one continuous voiceover track via ffmpeg concat filter.');
    bullet('**Step 6 — Video composition:** ffmpeg composes the final MP4: each background image is expanded into a video segment using `zoompan` (subtle 3% Ken Burns zoom effect), text overlays are composited, segments are joined with 0.3s crossfade dissolve transitions, and the stitched voiceover is laid as the audio track.');
    bullet('**Fallback handling:** If Replicate fails → gradient backgrounds. If TTS fails for a segment → silent audio for that segment\'s duration. Errors propagate with actual messages instead of generic "Nothing to render".');

    h3('9.3 Story Rendering');
    p('Stories are rendered as 1080x1920 PNG frames (9:16 vertical) with interactive overlay mockups for polls, questions, sliders, and DM triggers.');

    h3('9.4 Source Code');
    const renderFiles = live?.sourceTree.rendering || [];
    renderFiles.forEach(f => {
      h4(`\`src/${f}\``);
      fileBlock(f);
    });
  }

  // ─── CONFIGURATION ───────────────────────────────
  if (inc('config')) {
    h2('10. Configuration');

    h3('10.1 Environment Variables (.env)');
    p('All configuration is centralized in `src/config/env.ts` which reads from `.env` and exports a frozen `CONFIG` object. Required variables are marked with **(required)**.');
    bullet('`ANTHROPIC_API_KEY` **(required)** — Anthropic API key for Claude AI. Get from console.anthropic.com.');
    bullet('`CLAUDE_MODEL` — Model identifier. Default: `claude-sonnet-4-5-20250929`. Can be any Claude model ID.');
    bullet('`INSTAGRAM_ACCESS_TOKEN` **(required for publishing)** — Long-lived Instagram access token (valid 60 days). Generated via Facebook Graph API Explorer → exchange for long-lived token.');
    bullet('`INSTAGRAM_BUSINESS_ACCOUNT_ID` **(required for publishing)** — Instagram Business Account ID. Found via Graph API: `GET /me/accounts` → page ID → `GET /{page-id}?fields=instagram_business_account`.');
    bullet('`REPLICATE_API_TOKEN` **(required for rendering)** — Replicate API token for Flux Schnell image generation. Get from replicate.com/account/api-tokens.');
    bullet('`CLOUDINARY_CLOUD_NAME` / `CLOUDINARY_API_KEY` / `CLOUDINARY_API_SECRET` **(required for publishing)** — Cloudinary credentials for asset CDN hosting.');
    bullet('`OPENAI_API_KEY` **(required for reel voiceover)** — OpenAI API key for per-segment TTS voiceover generation. Each reel segment gets its own TTS call and the audio duration drives visual timing. Reels will use silent audio per segment if not set.');
    bullet('`BUFFER_ACCESS_TOKEN` — Buffer API token for scheduled publishing. Optional: direct Instagram publishing is the default.');
    bullet('`APP_NICHE` — The active niche name (e.g., "indoor plants", "houseplant care"). Drives content topics.');
    bullet('`DASHBOARD_PORT` — Express server port. Default: 3847.');
    bullet('`CAROUSEL_SLIDE_COUNT` — Number of slides per carousel. Default: 10.');

    h3('10.2 Config Source Files');
    const configFiles = live?.sourceTree.config || [];
    configFiles.forEach(f => {
      h4(`\`src/${f}\``);
      fileBlock(f);
    });

    h3('10.3 Orchestrator Files');
    const orchFiles = live?.sourceTree.orchestrator || [];
    orchFiles.forEach(f => {
      h4(`\`src/${f}\``);
      fileBlock(f);
    });

    h3('10.4 Utility Files');
    const utilFiles = live?.sourceTree.utils || [];
    utilFiles.forEach(f => {
      h4(`\`src/${f}\``);
      fileBlock(f);
    });

    h3('10.5 Foundation Application — Cloning for a New Niche');
    p('This application is designed as a **foundation template**. ThePlantICU is the first deployment, but the architecture is completely niche-agnostic. To deploy a new Instagram theme page engine:');
    bullet('1. Clone the repository');
    bullet('2. Create a new `.env` file with the new page\'s Instagram credentials, API keys, and niche name');
    bullet('3. Run `npm run niches` to analyze 20 niches and select the best fit');
    bullet('4. Run `npm run design-system` to generate a brand visual system (colors, fonts, templates)');
    bullet('5. Create a Creative Brief in the dashboard with the new page\'s content direction');
    bullet('6. Create an AI Settings profile to tune prompt style and image generation');
    bullet('7. Run `npm run daily` or use the dashboard Pipeline tab to start generating content');
  }

  return L.join('\n');
}

function downloadMarkdown(content: string, filename: string) {
  const blob = new Blob([content], { type: 'text/markdown;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

// ─── Reusable UI Components ─────────────────────────

function SectionCard({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="bg-gray-900 border border-gray-800 rounded-xl overflow-hidden">
      <div className="px-6 py-4 border-b border-gray-800">
        <h3 className="text-lg font-semibold">{title}</h3>
      </div>
      <div className="px-6 py-5 space-y-4">{children}</div>
    </div>
  );
}

function FileEntry({ path, description }: { path: string; description: string }) {
  return (
    <div className="flex gap-3 py-2">
      <code className="text-purple-400 text-xs font-mono whitespace-nowrap flex-shrink-0">{path}</code>
      <span className="text-gray-400 text-sm">{description}</span>
    </div>
  );
}

function Tag({ children, color = 'purple' }: { children: React.ReactNode; color?: string }) {
  const colors: Record<string, string> = {
    purple: 'bg-purple-600/20 text-purple-400',
    green: 'bg-green-600/20 text-green-400',
    blue: 'bg-blue-600/20 text-blue-400',
    yellow: 'bg-yellow-600/20 text-yellow-400',
    pink: 'bg-pink-600/20 text-pink-400',
    orange: 'bg-orange-600/20 text-orange-400',
  };
  return (
    <span className={`px-2 py-0.5 text-xs font-medium rounded-full ${colors[color] || colors.purple}`}>
      {children}
    </span>
  );
}

function DownloadButton({ onClick, label }: { onClick: () => void; label: string }) {
  return (
    <button
      onClick={onClick}
      className="px-3 py-1 text-xs bg-gray-800 border border-gray-700 hover:border-green-600 hover:text-green-400 text-gray-400 rounded-lg transition-colors"
    >
      {label}
    </button>
  );
}

function LiveBadge({ label }: { label: string }) {
  return (
    <span className="px-2 py-0.5 text-xs font-medium bg-green-600/20 text-green-400 rounded-full animate-pulse">
      {label}
    </span>
  );
}

// ─── Section Renderers ───────────────────────────────

function OverviewSection() {
  return (
    <div className="space-y-6">
      <SectionCard title="What Is This Application?">
        <p className="text-gray-300 text-sm leading-relaxed">
          ThePlantICU Content Engine is an end-to-end AI-powered Instagram content automation platform
          built specifically for <strong className="text-green-400">@ThePlantICU</strong> — a faceless
          plant care theme page. It handles the entire content lifecycle: idea generation, script writing,
          visual rendering, approval workflow, publishing to Instagram, and analytics tracking.
        </p>
        <p className="text-gray-300 text-sm leading-relaxed">
          The system is designed as a <strong className="text-purple-400">foundation application</strong> that
          can be cloned and adapted for other niche Instagram theme pages. ThePlantICU is the first
          deployment, but the architecture is niche-agnostic.
        </p>
      </SectionCard>
      <SectionCard title="Core Intentions">
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {[
            { title: 'Zero-Face Content', desc: 'All content is faceless — no person on camera. AI generates backgrounds, text overlays, and voiceovers.' },
            { title: '100% Original', desc: 'Every piece is created from scratch. Built-in originality engine prevents reposts and detects similarity above 70%.' },
            { title: 'DM-First Growth', desc: 'Optimized for "sends per reach" — the #1 Instagram algorithm signal. Every post answers: "Who would DM this to whom?"' },
            { title: 'Human Approval Gate', desc: 'AI generates, but humans approve. Nothing publishes without explicit user action from this dashboard.' },
            { title: 'Full Automation Pipeline', desc: 'From idea to published post: trend scanning, content generation, visual rendering, and Instagram publishing.' },
            { title: 'Analytics Feedback Loop', desc: 'Pulls real metrics from Instagram Graph API, generates weekly scorecards, and feeds performance data back into content strategy.' },
          ].map((item, i) => (
            <div key={i} className="bg-gray-800 rounded-lg p-4">
              <h4 className="text-sm font-medium text-gray-200 mb-1">{item.title}</h4>
              <p className="text-xs text-gray-400">{item.desc}</p>
            </div>
          ))}
        </div>
      </SectionCard>
      <SectionCard title="Tech Stack">
        <div className="flex flex-wrap gap-2">
          {['TypeScript','Node.js','Express','React','Vite','Tailwind CSS','SQLite (better-sqlite3)','Puppeteer','ffmpeg','Commander.js','Claude API (Anthropic)','Instagram Graph API','Replicate (Flux Schnell)','Cloudinary','OpenAI TTS','Buffer API'].map((t) => (
            <span key={t} className="px-3 py-1 bg-gray-800 border border-gray-700 rounded-full text-xs text-gray-300">{t}</span>
          ))}
        </div>
      </SectionCard>
    </div>
  );
}

function ArchitectureSection({ live }: { live: LiveData | null }) {
  return (
    <div className="space-y-6">
      <SectionCard title="Source File Tree">
        {live ? (
          <div className="space-y-4">
            <div className="flex items-center gap-2 mb-2">
              <LiveBadge label="Live from filesystem" />
              <span className="text-gray-500 text-xs">
                {live.sourceTree.entryPoints.length + live.sourceTree.config.length + live.sourceTree.database.length +
                  live.sourceTree.integrations.length + live.sourceTree.orchestrator.length + live.sourceTree.rendering.length +
                  live.sourceTree.utils.length + live.sourceTree.dashboard.length +
                  live.sourceTree.modules.reduce((s, m) => s + m.files.length, 0)} files total
              </span>
            </div>
            {[
              { label: 'Entry Points', files: live.sourceTree.entryPoints, prefix: 'src/' },
              { label: 'Config', files: live.sourceTree.config, prefix: 'src/' },
              { label: 'Database', files: live.sourceTree.database, prefix: 'src/' },
              { label: 'Integrations', files: live.sourceTree.integrations, prefix: 'src/' },
              { label: 'Orchestrator', files: live.sourceTree.orchestrator, prefix: 'src/' },
              { label: 'Rendering', files: live.sourceTree.rendering, prefix: 'src/' },
              { label: 'Utils', files: live.sourceTree.utils, prefix: 'src/' },
              { label: 'Dashboard', files: live.sourceTree.dashboard, prefix: 'src/' },
            ].map(group => (
              <div key={group.label}>
                <span className="text-gray-500 text-xs uppercase tracking-wide">{group.label} ({group.files.length})</span>
                <div className="flex flex-wrap gap-1.5 mt-1">
                  {group.files.map(f => (
                    <code key={f} className="text-xs font-mono px-2 py-0.5 bg-gray-800 rounded text-purple-400">{group.prefix}{f}</code>
                  ))}
                </div>
              </div>
            ))}
            <div>
              <span className="text-gray-500 text-xs uppercase tracking-wide">Modules ({live.sourceTree.modules.length})</span>
              {live.sourceTree.modules.map(m => (
                <div key={m.dir} className="mt-1 ml-2">
                  <span className="text-green-400 text-xs font-mono">{m.dir}/</span>
                  <span className="text-gray-500 text-xs ml-2">{m.files.join(', ')}</span>
                </div>
              ))}
            </div>
          </div>
        ) : (
          <p className="text-gray-500 text-sm">Loading live file tree...</p>
        )}
      </SectionCard>
      <SectionCard title="Key Design Decisions">
        <div className="space-y-3 text-sm text-gray-300">
          <div><strong className="text-gray-200">SQLite over Postgres:</strong> Single-file database, zero setup, perfect for single-operator tool. WAL mode for concurrent reads.</div>
          <div><strong className="text-gray-200">Puppeteer for rendering:</strong> HTML/CSS templates rendered to PNG screenshots. Full control over typography, layouts, and brand consistency.</div>
          <div><strong className="text-gray-200">Module numbering (00-10):</strong> Sequential pipeline stages. Each module is self-contained with its own prompts file, engine file, and types.</div>
          <div><strong className="text-gray-200">Creative Brief + AI Settings split:</strong> Brief = what content to make (angles, mood, competitors). AI Settings = how the AI behaves (prompts, temperature, image style).</div>
        </div>
      </SectionCard>
    </div>
  );
}

function DataFlowSection() {
  return (
    <div className="space-y-6">
      <SectionCard title="Content Pipeline Flow">
        <div className="space-y-1 font-mono text-xs">
          {[
            { step: '1', label: 'Niche Selection', detail: 'Module 01 analyzes 20 niches, scores on 6 metrics, selects best fit', color: 'text-blue-400' },
            { step: '2', label: 'Originality Rules', detail: 'Module 00 generates guardrails — transformation rules, red lines, plagiarism thresholds', color: 'text-blue-400' },
            { step: '3', label: 'Viral Blueprint', detail: 'Module 02 generates 15 content ideas (8 carousel + 7 reel) with hooks & send triggers', color: 'text-yellow-400' },
            { step: '4', label: 'Trend Check', detail: 'Module 04 scans for trending topics in niche — urgency-ranked with original angles', color: 'text-yellow-400' },
            { step: '5', label: 'Content Options', detail: 'Module 04 presents 5 variations for user selection (different angles/hooks)', color: 'text-yellow-400' },
            { step: '6', label: 'Script Building', detail: 'Module 03 converts chosen idea into production-ready carousel/reel/story script', color: 'text-green-400' },
            { step: '7', label: 'Approval Gate', detail: 'User reviews script in dashboard — approve, reject, or edit', color: 'text-purple-400' },
            { step: '8', label: 'Visual Rendering', detail: 'Puppeteer renders slides/overlays, Replicate generates AI backgrounds, ffmpeg composes video', color: 'text-pink-400' },
            { step: '9', label: 'CDN Upload', detail: 'Cloudinary hosts rendered assets with public HTTPS URLs', color: 'text-pink-400' },
            { step: '10', label: 'Publishing', detail: 'Instagram Graph API publishes carousel/reel. Buffer for scheduling.', color: 'text-green-400' },
            { step: '11', label: 'Analytics', detail: 'Graph API pulls impressions, reach, sends, saves. Weekly scorecard generated.', color: 'text-blue-400' },
          ].map((s) => (
            <div key={s.step} className="flex gap-3 py-2 border-b border-gray-800/50 last:border-0">
              <span className="text-gray-600 w-6 text-right">{s.step}.</span>
              <span className={`w-36 flex-shrink-0 font-semibold ${s.color}`}>{s.label}</span>
              <span className="text-gray-400">{s.detail}</span>
            </div>
          ))}
        </div>
      </SectionCard>
      <SectionCard title="Status Lifecycle">
        <div className="font-mono text-xs text-gray-400 bg-gray-800 rounded-lg p-4 overflow-x-auto whitespace-pre">{`Content Idea Status:
  generated → scripted → approved → designed → published
                  ↘ rejected → archived

Pipeline Phase:
  idle → generating → rendering → awaiting_approval → publishing → idle

Content Calendar:
  scheduled → published | cancelled`}</div>
      </SectionCard>
      <SectionCard title="AI Settings Impact">
        <div className="space-y-2 text-sm text-gray-300">
          <p><Tag color="purple">System Prompt</Tag> Overrides the Claude personality used in Module 03 (carousel, reel, story builders)</p>
          <p><Tag color="blue">Carousel Design Instruction</Tag> Controls how Claude writes the designNotes field for each carousel slide</p>
          <p><Tag color="blue">Reel Visual Instruction</Tag> Controls how Claude writes the visual field for reel hook, body, and CTA</p>
          <p><Tag color="green">Style Prefix</Tag> Prepended to every Replicate image prompt</p>
          <p><Tag color="green">Style Suffix</Tag> Appended to every Replicate image prompt</p>
          <p><Tag color="yellow">Negative Prompt</Tag> Added as "Do not include: ..." to Replicate prompts</p>
          <p><Tag color="orange">Temperature</Tag> Controls Claude's creativity (0.0 = focused, 1.0 = creative)</p>
        </div>
      </SectionCard>
    </div>
  );
}

function PagesSection() {
  const pages = [
    { name: 'Pipeline', desc: 'Real-time pipeline status showing current phase, errors, and content package preview with manual trigger.', features: ['Phase status cards', 'Error display', 'Package preview', 'Manual trigger', 'Auto-refresh'] },
    { name: 'Content', desc: 'Unified content hub with thumbnails, approve/render/publish/schedule actions, caption & hashtag preview.', features: ['Thumbnail grid', 'Approve/Render/Publish', 'Post to Instagram', 'Schedule', 'Regenerate'] },
    { name: 'Brief', desc: 'Creative direction: angles, mood, visual style, competitor links, target emotions. CRUD with active toggle.', features: ['Profile CRUD', 'Active highlighting', 'Competitor links', 'Content angles', 'Past briefs'] },
    { name: 'AI Settings', desc: 'Claude system prompt, image style prefix/suffix, negative prompt, temperature. Multiple profiles.', features: ['System prompt editor', 'Image style', 'Negative prompt', 'Temperature', 'Reset to Default'] },
    { name: 'Analytics', desc: '30-day overview: reach, sends, saves, engagement. Per-post metrics table.', features: ['Summary cards', 'Per-post table', 'Sends/reach', 'Refresh trigger'] },
    { name: 'Scorecard', desc: 'Weekly KPI dashboard with traffic-light health scoring.', features: ['Traffic-light KPIs', 'Historical trend', 'Health scoring'] },
    { name: 'Revenue', desc: 'Revenue tracking with manual entry, source breakdown, AI strategy generator.', features: ['Revenue entry', 'Source breakdown', 'AI strategy'] },
    { name: 'Build Checklist', desc: '70+ item progress tracker across 18 sections.', features: ['Progress bars', 'Status badges', 'Completion summary'] },
    { name: 'Build Document', desc: 'This page — auto-updating documentation with per-section download.', features: ['Live data', 'Per-section download', 'Full download'] },
  ];
  return (
    <div className="space-y-4">
      {pages.map(pg => (
        <SectionCard key={pg.name} title={pg.name}>
          <p className="text-sm text-gray-300">{pg.desc}</p>
          <div className="flex flex-wrap gap-2 mt-2">{pg.features.map(f => <Tag key={f} color="green">{f}</Tag>)}</div>
        </SectionCard>
      ))}
    </div>
  );
}

function ModulesSection({ live }: { live: LiveData | null }) {
  const modules = live?.sourceTree.modules || [];
  return (
    <div className="space-y-4">
      {live && <div className="flex items-center gap-2"><LiveBadge label="Live from filesystem" /><span className="text-gray-500 text-xs">{modules.length} modules discovered</span></div>}
      {modules.map(m => {
        const info = moduleDescriptions[m.dir];
        return (
          <SectionCard key={m.dir} title={`Module ${m.dir}${info ? ': ' + info.name : ''}`}>
            {info && <p className="text-sm text-gray-300">{info.description}</p>}
            {!info && <p className="text-sm text-yellow-400">New module — no description yet.</p>}
            <div className="mt-3">
              <span className="text-gray-500 text-xs uppercase tracking-wide">Files ({m.files.length})</span>
              <div className="flex flex-wrap gap-2 mt-1">
                {m.files.map(f => <code key={f} className="text-xs font-mono px-2 py-0.5 bg-gray-800 rounded text-purple-400">{f}</code>)}
              </div>
            </div>
            {info && (
              <div className="mt-2">
                <span className="text-gray-500 text-xs uppercase tracking-wide">Key Exports</span>
                <div className="flex flex-wrap gap-2 mt-1">
                  {info.exports.map(e => <code key={e} className="text-xs font-mono px-2 py-0.5 bg-gray-800 rounded text-green-400">{e}</code>)}
                </div>
              </div>
            )}
          </SectionCard>
        );
      })}
    </div>
  );
}

function IntegrationsSection({ live }: { live: LiveData | null }) {
  const integrationFiles = live?.sourceTree.integrations || [];
  const integrations = [
    { name: 'Anthropic Claude API', file: 'integrations/claude-client.ts', model: 'Claude Sonnet 4.5 (configurable)', usage: 'All content generation — ideas, scripts, design systems, strategies, DM flows, platform adaptation, trend scanning', features: ['askClaude() — text responses with cost tracking', 'askClaudeJSON<T>() — structured JSON output with repair logic', 'Truncated JSON auto-repair', 'Token usage and cost estimation', 'Dynamic temperature via AI Settings'] },
    { name: 'Instagram Graph API (Meta)', file: 'integrations/instagram-api.ts', model: 'API v22.0', usage: 'Publishing content (images, carousels, reels) and fetching performance analytics', features: ['publishImagePost()', 'publishCarouselPost()', 'publishReel()', 'getMediaInsights()', 'getRecentMedia()', 'Long-lived token management'] },
    { name: 'Replicate (Flux Schnell)', file: 'integrations/replicate-api.ts', model: 'black-forest-labs/flux-schnell', usage: 'AI background image generation for carousel slides and reel frames', features: ['generateBackground()', 'Aspect ratio: 9:16 / 1:1', 'AI Settings style injection', 'URL and ReadableStream output handling'] },
    { name: 'Cloudinary', file: 'integrations/cloudinary-api.ts', model: 'Upload API', usage: 'CDN hosting for rendered images and videos', features: ['uploadImage()', 'uploadVideo()', 'uploadImages()', 'Folder organization'] },
    { name: 'OpenAI TTS', file: 'integrations/tts-api.ts', model: 'tts-1', usage: 'Per-segment reel voiceover generation (audio drives visual timing)', features: ['generateSpeech()', '6 voice options', 'MP3 output', 'Per-segment TTS calls', 'ffprobe duration probing', 'Audio-driven segment timing'] },
    { name: 'Buffer', file: 'integrations/buffer-api.ts', model: 'API v1', usage: 'Optional social media scheduling', features: ['getProfiles()', 'createPost() / schedulePost()', 'addToQueue()', 'getPostingSchedule()'] },
    { name: 'Canva Connect', file: 'integrations/canva-api.ts', model: 'Connect API', usage: 'Optional design creation and spec generation', features: ['createDesign()', 'generateDesignSpec()', 'Requires API approval'] },
  ];

  // Show any integration files not covered by static list
  const knownFiles = new Set(integrations.map(i => i.file));
  const newFiles = integrationFiles.filter(f => !knownFiles.has(f));

  return (
    <div className="space-y-4">
      {live && <div className="flex items-center gap-2"><LiveBadge label="Live" /><span className="text-gray-500 text-xs">{integrationFiles.length} integration files</span></div>}
      {integrations.map(intg => (
        <SectionCard key={intg.name} title={intg.name}>
          <div className="flex flex-wrap gap-3 text-xs mb-3">
            <span className="text-gray-500">File: <code className="text-purple-400">src/{intg.file}</code></span>
            <span className="text-gray-500">Model: <code className="text-blue-400">{intg.model}</code></span>
          </div>
          <p className="text-sm text-gray-300">{intg.usage}</p>
          <div className="mt-3 space-y-1">
            {intg.features.map((f, i) => (
              <div key={i} className="flex items-start gap-2 text-xs text-gray-400"><span className="text-green-400 mt-0.5">-</span><span>{f}</span></div>
            ))}
          </div>
        </SectionCard>
      ))}
      {newFiles.length > 0 && (
        <SectionCard title="New Integration Files">
          {newFiles.map(f => <div key={f} className="flex items-center gap-2"><code className="text-xs font-mono text-yellow-400">src/{f}</code><span className="text-yellow-400 text-xs">— needs description</span></div>)}
        </SectionCard>
      )}
    </div>
  );
}

function ApiEndpointsSection({ live }: { live: LiveData | null }) {
  const routes = live?.routes.filter(r => r.path.startsWith('/api/')) || [];
  const methodColors: Record<string, string> = {
    GET: 'bg-green-600/20 text-green-400',
    POST: 'bg-blue-600/20 text-blue-400',
    PUT: 'bg-yellow-600/20 text-yellow-400',
    DELETE: 'bg-red-600/20 text-red-400',
  };

  // Group routes by path prefix
  const groups: Record<string, LiveRoute[]> = {};
  routes.forEach(r => {
    const parts = r.path.replace('/api/', '').split('/');
    const group = parts[0] || 'other';
    if (!groups[group]) groups[group] = [];
    groups[group].push(r);
  });

  return (
    <div className="space-y-4">
      <div className="bg-gray-900 border border-gray-800 rounded-xl p-4 flex items-center gap-3">
        {live && <LiveBadge label="Live from Express" />}
        <p className="text-sm text-gray-400">
          <strong className="text-gray-200">{routes.length} endpoints</strong> served on port {live?.configSummary.dashboardPort || 3847}.
          All return JSON. POST/PUT accept <code className="text-purple-400">application/json</code>.
        </p>
      </div>
      {Object.entries(groups).map(([group, endpoints]) => (
        <SectionCard key={group} title={group.replace(/-/g, ' ').replace(/\b\w/g, c => c.toUpperCase())}>
          {endpoints.map((ep, i) => {
            const key = `${ep.method} ${ep.path}`;
            const desc = routeDescriptions[key] || '';
            return (
              <div key={i} className="flex items-start gap-3 py-2 border-b border-gray-800/50 last:border-0">
                <span className={`px-2 py-0.5 text-xs font-mono font-bold rounded ${methodColors[ep.method] || 'bg-gray-700 text-gray-300'}`}>{ep.method}</span>
                <code className="text-purple-400 text-xs font-mono flex-shrink-0">{ep.path}</code>
                <span className="text-gray-400 text-sm">{desc || <span className="text-yellow-400">undocumented</span>}</span>
              </div>
            );
          })}
        </SectionCard>
      ))}
    </div>
  );
}

function DatabaseSection({ live }: { live: LiveData | null }) {
  const tables = live?.tables || [];
  const migrations = live?.migrations || [];

  return (
    <div className="space-y-6">
      <div className="bg-gray-900 border border-gray-800 rounded-xl p-4 flex items-center gap-3">
        {live && <LiveBadge label="Live from SQLite" />}
        <p className="text-sm text-gray-400">
          <strong className="text-gray-200">{tables.length} tables</strong> in <code className="text-purple-400">data/ig-engine.db</code> — WAL mode, foreign keys enabled.
          {' '}<strong className="text-gray-200">{migrations.length} migrations</strong> applied.
        </p>
      </div>

      {migrations.length > 0 && (
        <SectionCard title="Migrations">
          {migrations.map(m => (
            <div key={m.version} className="flex items-center gap-3 py-1 text-xs">
              <span className="text-green-400 font-mono w-8">v{m.version}</span>
              <span className="text-gray-300">{m.name}</span>
              <span className="text-gray-600 ml-auto">{m.applied_at}</span>
            </div>
          ))}
        </SectionCard>
      )}

      {tables.map(t => (
        <SectionCard key={t.name} title={t.name}>
          <div className="flex items-center gap-3 mb-3">
            <p className="text-sm text-gray-300">{tableDescriptions[t.name] || <span className="text-yellow-400">New table — needs description.</span>}</p>
            <span className="text-xs text-gray-500 whitespace-nowrap ml-auto">{t.rowCount} rows</span>
          </div>
          <div className="overflow-x-auto">
            <table className="w-full text-xs">
              <thead>
                <tr className="border-b border-gray-800">
                  <th className="text-left py-2 px-2 text-gray-500 font-medium">Column</th>
                  <th className="text-left py-2 px-2 text-gray-500 font-medium">Type</th>
                  <th className="text-left py-2 px-2 text-gray-500 font-medium">Nullable</th>
                  <th className="text-left py-2 px-2 text-gray-500 font-medium">Default</th>
                  <th className="text-left py-2 px-2 text-gray-500 font-medium">PK</th>
                </tr>
              </thead>
              <tbody>
                {t.columns.map(c => (
                  <tr key={c.name} className="border-b border-gray-800/50">
                    <td className="py-1.5 px-2 font-mono text-purple-400">{c.name}</td>
                    <td className="py-1.5 px-2 text-gray-400">{c.type || 'TEXT'}</td>
                    <td className="py-1.5 px-2 text-gray-400">{c.notnull ? 'NO' : 'YES'}</td>
                    <td className="py-1.5 px-2 text-gray-500 font-mono">{c.dflt_value || '-'}</td>
                    <td className="py-1.5 px-2">{c.pk ? <span className="text-yellow-400">PK</span> : ''}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </SectionCard>
      ))}

      {tables.length === 0 && (
        <div className="bg-gray-900 border border-gray-800 rounded-xl p-8 text-center">
          <p className="text-gray-500">Start the server to see live database schema.</p>
        </div>
      )}
    </div>
  );
}

function RenderingSection() {
  return (
    <div className="space-y-6">
      <SectionCard title="Rendering Pipeline Overview">
        <p className="text-sm text-gray-300">The rendering pipeline converts JSON scripts into publishable visual assets. Carousels become PNG slides, reels become MP4 videos, and stories become PNG frames. All assets are uploaded to Cloudinary for public HTTPS URLs that Instagram Graph API requires.</p>
      </SectionCard>
      <SectionCard title="Carousel Rendering">
        <FileEntry path="src/rendering/carousel-renderer.ts" description="Generates 1080x1080 PNG slides via Puppeteer" />
        <div className="text-sm text-gray-400 space-y-1 mt-2">
          <p>1. Parse script JSON into slide objects (hook, value, CTA types)</p>
          <p>2. For each slide: generate AI background via Replicate (Flux Schnell, 1:1 aspect)</p>
          <p>3. Render HTML template with background image, headline, body, brand colors/fonts</p>
          <p>4. Screenshot with Puppeteer at 1080x1080px resolution</p>
          <p>5. Upload all PNGs to Cloudinary</p>
        </div>
      </SectionCard>
      <SectionCard title="Reel Rendering (Audio-Driven Sync)">
        <FileEntry path="src/rendering/reel-renderer.ts" description="Generates MP4 video with per-segment TTS, AI backgrounds, and ffmpeg composition" />
        <div className="text-sm text-gray-400 space-y-1 mt-2">
          <p>1. Parse script JSON into segments (hook, body[], CTA) with voiceover text per segment</p>
          <p>2. Generate TTS audio per segment via OpenAI — probe each clip&apos;s duration with ffprobe</p>
          <p>3. Set each visual segment duration = audio duration + 0.3s buffer (audio drives timing)</p>
          <p>4. Generate AI background images via Replicate Flux Schnell (9:16 aspect)</p>
          <p>5. Render text overlay PNGs via Puppeteer with step indicators</p>
          <p>6. Concatenate per-segment audio clips into one voiceover track</p>
          <p>7. Compose MP4 with ffmpeg: zoompan Ken Burns effect + crossfade transitions + synced audio</p>
          <p>8. Fallback: gradient backgrounds if Replicate fails, silent audio if TTS fails per segment</p>
        </div>
      </SectionCard>
      <SectionCard title="Story Rendering">
        <FileEntry path="src/rendering/story-renderer.ts" description="Generates 1080x1920 PNG frames with interactive overlays" />
        <div className="text-sm text-gray-400 space-y-1 mt-2">
          <p>1. Parse story sequence into slides</p>
          <p>2. Render each slide as 1080x1920 PNG (9:16 vertical)</p>
          <p>3. Add interactive overlays: polls, questions, sliders, DM triggers</p>
          <p>4. Semi-transparent text overlays with brand styling</p>
        </div>
      </SectionCard>
      <SectionCard title="Supporting Files">
        <FileEntry path="src/rendering/templates.ts" description="HTML/CSS templates for all slide types" />
        <div className="flex flex-wrap gap-2 mt-2">
          <Tag color="blue">hookSlideHtml()</Tag><Tag color="blue">valueSlideHtml()</Tag><Tag color="blue">ctaSlideHtml()</Tag><Tag color="pink">storyOverlayHtml()</Tag><Tag color="purple">reelOverlayHtml()</Tag>
        </div>
        <FileEntry path="src/rendering/asset-pipeline.ts" description="Orchestrates rendering + Cloudinary upload + database storage. Propagates actual render errors to the dashboard." />
        <FileEntry path="src/rendering/browser-pool.ts" description="Puppeteer instance pooling for efficient concurrent rendering" />
      </SectionCard>
    </div>
  );
}

function ConfigSection({ live }: { live: LiveData | null }) {
  return (
    <div className="space-y-6">
      {live && (
        <SectionCard title="Active Configuration">
          <div className="flex items-center gap-2 mb-3"><LiveBadge label="Live" /></div>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
            {[
              { label: 'Niche', value: live.configSummary.niche || '(not set)' },
              { label: 'Model', value: live.configSummary.model },
              { label: 'Port', value: String(live.configSummary.dashboardPort) },
              { label: 'Carousel Slides', value: String(live.configSummary.carouselSlideCount) },
            ].map(c => (
              <div key={c.label} className="bg-gray-800 rounded-lg p-3">
                <span className="text-gray-500 text-xs uppercase">{c.label}</span>
                <p className="text-sm text-gray-200 font-medium mt-1">{c.value}</p>
              </div>
            ))}
          </div>
          <div className="grid grid-cols-2 md:grid-cols-5 gap-3 mt-3">
            {[
              { label: 'Instagram', ok: live.configSummary.hasInstagramToken },
              { label: 'Replicate', ok: live.configSummary.hasReplicateToken },
              { label: 'Cloudinary', ok: live.configSummary.hasCloudinary },
              { label: 'OpenAI TTS', ok: live.configSummary.hasOpenAI },
              { label: 'Buffer', ok: live.configSummary.hasBuffer },
            ].map(s => (
              <div key={s.label} className={`rounded-lg p-3 text-center ${s.ok ? 'bg-green-900/20 border border-green-800' : 'bg-gray-800 border border-gray-700'}`}>
                <span className={`text-xs font-medium ${s.ok ? 'text-green-400' : 'text-gray-500'}`}>{s.label}</span>
                <p className={`text-sm font-bold mt-1 ${s.ok ? 'text-green-400' : 'text-gray-600'}`}>{s.ok ? 'Connected' : 'Not set'}</p>
              </div>
            ))}
          </div>
        </SectionCard>
      )}
      <SectionCard title="Environment Variables (.env)">
        <div className="space-y-3 text-sm">
          {[
            { group: 'AI / Anthropic', vars: ['ANTHROPIC_API_KEY — Claude API key', 'CLAUDE_MODEL — Model ID (default: claude-sonnet-4-5-20250929)'] },
            { group: 'Instagram Graph API', vars: ['INSTAGRAM_ACCESS_TOKEN — Long-lived token (60 days)', 'INSTAGRAM_BUSINESS_ACCOUNT_ID — Business account ID'] },
            { group: 'Image Generation', vars: ['REPLICATE_API_TOKEN — Replicate API token (Flux Schnell)'] },
            { group: 'Media Hosting', vars: ['CLOUDINARY_CLOUD_NAME — Cloudinary account', 'CLOUDINARY_API_KEY — API key', 'CLOUDINARY_API_SECRET — API secret'] },
            { group: 'Audio / TTS', vars: ['OPENAI_API_KEY — OpenAI TTS (tts-1 model)'] },
            { group: 'Scheduling (Optional)', vars: ['BUFFER_ACCESS_TOKEN — Buffer scheduling API'] },
            { group: 'Application', vars: ['APP_NICHE — Active niche name', 'DASHBOARD_PORT — Server port (default: 3847)', 'CAROUSEL_SLIDE_COUNT — Slides per carousel (default: 10)'] },
          ].map(g => (
            <div key={g.group}>
              <h4 className="text-gray-300 font-medium mb-1">{g.group}</h4>
              <div className="font-mono text-xs text-gray-400 bg-gray-800 rounded-lg p-3 space-y-1">
                {g.vars.map(v => <p key={v}>{v}</p>)}
              </div>
            </div>
          ))}
        </div>
      </SectionCard>
      <SectionCard title="Config Files">
        <FileEntry path="src/config/env.ts" description="Centralizes all .env variables into typed CONFIG object. Frozen on load." />
        <FileEntry path="src/config/brand.ts" description="Brand system cache: colors, fonts, voice, visual style. Loaded from database." />
        <FileEntry path="src/config/niche.ts" description="Active niche cache: scoring, monetization paths, content mix, send triggers." />
        <FileEntry path="src/config/ai-settings.ts" description="Dynamic AI settings: system prompt, image style, temperature. Fresh DB query each call." />
      </SectionCard>
      <SectionCard title="Foundation Application">
        <p className="text-sm text-gray-300 leading-relaxed">This app is a <strong className="text-purple-400">foundation template</strong> for deploying multiple Instagram theme page engines. ThePlantICU is the first deployment. To create a new page engine:</p>
        <div className="mt-3 space-y-2 text-sm text-gray-400">
          <p>1. Clone the repository</p>
          <p>2. Update <code className="text-purple-400">.env</code> with new Instagram credentials and niche</p>
          <p>3. Run <code className="text-purple-400">npm run niches</code> to analyze and select a new niche</p>
          <p>4. Run <code className="text-purple-400">npm run design-system</code> to generate brand visuals</p>
          <p>5. Create a Creative Brief and AI Settings profile for the new page</p>
          <p>6. Start generating content</p>
        </div>
      </SectionCard>
    </div>
  );
}

// ─── Main Component ──────────────────────────────────

export default function BuildDoc() {
  const [activeSection, setActiveSection] = useState<SectionId>('overview');
  const [live, setLive] = useState<LiveData | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetch('/api/build-doc')
      .then(r => r.json())
      .then(data => { setLive(data); setLoading(false); })
      .catch(() => setLoading(false));
  }, []);

  const handleDownloadSection = (id: SectionId) => {
    const label = sectionList.find(s => s.id === id)?.label || id;
    const md = generateMarkdown(id, live);
    downloadMarkdown(md, `theplanticu-${id}.md`);
  };

  const handleDownloadAll = () => {
    const md = generateMarkdown('all', live);
    downloadMarkdown(md, 'theplanticu-build-document.md');
  };

  const renderSection = () => {
    switch (activeSection) {
      case 'overview': return <OverviewSection />;
      case 'architecture': return <ArchitectureSection live={live} />;
      case 'dataflow': return <DataFlowSection />;
      case 'pages': return <PagesSection />;
      case 'modules': return <ModulesSection live={live} />;
      case 'integrations': return <IntegrationsSection live={live} />;
      case 'api': return <ApiEndpointsSection live={live} />;
      case 'database': return <DatabaseSection live={live} />;
      case 'rendering': return <RenderingSection />;
      case 'config': return <ConfigSection live={live} />;
    }
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-2xl font-bold">Build Document</h2>
          <p className="text-gray-400 text-sm mt-1">
            Complete technical documentation for ThePlantICU Content Engine
            {live && <span className="text-green-400 ml-2">- Live data loaded</span>}
            {loading && <span className="text-yellow-400 ml-2">- Loading...</span>}
          </p>
        </div>
        <div className="flex gap-2">
          <DownloadButton onClick={() => handleDownloadSection(activeSection)} label="Download Section" />
          <button
            onClick={handleDownloadAll}
            className="px-4 py-2 bg-green-600 hover:bg-green-500 rounded-lg text-sm font-medium transition-colors"
          >
            Download Full Doc
          </button>
        </div>
      </div>

      {/* Section Navigation */}
      <div className="flex gap-1 overflow-x-auto pb-1">
        {sectionList.map((s) => (
          <button
            key={s.id}
            onClick={() => setActiveSection(s.id)}
            className={`px-3 py-1.5 text-xs font-medium rounded-lg transition-colors whitespace-nowrap ${
              activeSection === s.id
                ? 'bg-green-600 text-white'
                : 'bg-gray-800 text-gray-400 hover:bg-gray-700 hover:text-gray-200'
            }`}
          >
            {s.label}
          </button>
        ))}
      </div>

      {/* Active Section */}
      {renderSection()}
    </div>
  );
}
